version: "3.7"
services:
  app:
    build:
      args:
        user: eduard
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    restart: unless-stopped
    working_dir: /var/www/
    command: bash -c 'sleep 5 && php artisan migrate' # migrations will run at startup
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:5.7
    container_name: ${APP_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/ #this will make the storage persistent
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/ #this will first populate the database
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - db
    networks:
      - app-net

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ${APP_NAME}-phpmyadmin
      ports:
        - "7000:80"
      links:
        - db:db
      environment:
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        PMA_USER: ${DB_USERNAME} # comment this line to disable auto-login
        PMA_PASSWORD: ${DB_PASSWORD} # comment this line to disable auto-login
      depends_on:
        - db
      networks:
        - app-net

networks:
  app-net:
    driver: bridge
